# Generated by Django 4.0.6 on 2022-07-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='preview_image',
            field=models.ImageField(null=True, upload_to='preview_articles'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to='articles'),
        ),
    ]
