# Generated by Django 4.0.6 on 2022-07-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_articles_preview_image_alter_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
