# Generated by Django 4.0.6 on 2022-07-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_articles_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='preview_articles'),
        ),
    ]
