# Generated by Django 4.0.6 on 2022-07-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_articles_image_alter_articles_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='preview_image',
            field=models.ImageField(null=True, upload_to='preview_articles'),
        ),
    ]
