# Generated by Django 4.0.6 on 2022-07-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_articles_image_alter_articles_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='image',
        ),
    ]
